"""Initial migrations

Revision ID: 010220d33d20
Revises: b587e3e88581
Create Date: 2022-06-19 16:20:15.536446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010220d33d20'
down_revision = 'b587e3e88581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=100), nullable=True))
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
